[diesel]
username = "ENgsxyMbeqVGvGzTCpVdkZmsjz/VCDeF+NWHlRk3Hk0="
password = "EuoTNvCvp5imhOR2TZDe/fnKDxfoPK+EORSqfGvafZk="
store_id = "7b0fb2ac-51bd-47ea-847e-cfb1584b4aa2"

[hurley]
username = "CtAAy94MhKTJClgAwEfQL9LfkM14CegkeUbpBfhwt68="
password = "AmlbcKtg1WQsLuivLpjyOTVizNrijZiXY6vVJoT5a1U="
store_id = "a504304c-ad27-4b9b-8625-92a314498e64"

[jeep_apparel]
username = "+w3K5hLq56MQ4ijqFH78lV0xQCTTzP9mNAqToCUL9Cw="
password = "l2+ozGqsA6PX7MSHrl4OMwZRTieKzUpJVWv/WYye8iA="
store_id = "80f123d6-f9de-45b9-938c-61c0a358f205"

[superdry]
username = "zcUrzwFh2QwtH1yEJixFXtUA4XGQyx2wbNVLpYTzZ8M="
password = "92Av8tHsbq2XLEZZeRwYNsPFSkca+dD1cwRQs79rooM="
store_id = "b112948b-0390-4833-8f41-47f997c5382c"

[reebok]
username = "9oZ10dMWlyQpEmS0Kw6xhIcKYXw8lB2az3Q0Zb+KBAw="
password = "Cq/Zn86P7FT3EN0C5qzOewAQssyvrDSbkzmQBSAOrMY="
store_id = "963f57af-6f46-4d6d-b07c-dc4aa684cdfa"

[levis]
username = "4IQbm0CgLBZQkzliPnwWnjCQqgEdXsP6mVQ6q7nX24Y="
password = "70JK3u4z/lxrGdpdSUE4csPfzlg/wgGTcuAgUgbd+j4="
store_id = "ea344f50-5af3-4de1-814c-0c45171a2353"
